config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  namespace :api do
    resources :code, only: [:create]
    match 'code/status/:id/:hash', :to => 'code#status', :as => :code_status, :via => :get    
  end

  match 'code', :to => 'index#code', :as => :code, :via => :get
  match 'code/process', :to => 'index#process_code', :as => :process_code, :via => :post  
  match 'code/error', :to => 'index#code_error', :as => :code_error, :via => :get  
  match 'code/token', :to => 'index#code_token', :as => :code_token, :via => :get
  
  match 'code/token/save', :to => 'index#code_token_save', :as => :code_token_save, :via => :post  
  match 'code/token/error', :to => 'index#code_token_error', :as => :code_token_error, :via => :get    

  match 'code/token/done', :to => 'index#code_token_done', :as => :code_token_done, :via => :get      

end

app/models/code.rb
class Code < ActiveRecord::Base

	before_create :generate_code, :generate_state

	protected

	def generate_code
		self.code = loop do
			random_code = SecureRandom.hex(4)
			break random_code unless Code.where(code: random_code).exists?
		end
	end

	def generate_state
		self.state = loop do
			state_code = SecureRandom.hex(16)
			break state_code unless Code.where(state: state_code).exists?
		end
	end	
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base

	skip_before_filter :verify_authenticity_token
	# http_basic_authenticate_with name: "EXt86P7kUdrPZh2y89vk4yr889a77A8C", password: "rNJ46aBv7SMCdGHhQvcm6HxbmzbgtmmM"
	
	respond_to :json
end

app/controllers/api/code_controller.rb
class Api::CodeController < Api::BaseController

	def create
		@code = Code.new
		@code.save
	end

	def status

		@success = false		
		if !params.has_key?(:id) || !params.has_key?(:hash)
			return
		end

		hash = Digest::SHA1.hexdigest "#{params[:id]}#{Rails.application.secrets.twitch_client_secret}"
		puts hash

		if hash != params[:hash]
			return
		end

		@code = Code.where(:code => params[:id]).first
		if @code == nil
			return
		end

		@success = true
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

	def index
	end

	def code
	end

	def code_error
	end

	def code_token
	end	

	def code_token_save

		# Example hash
		# #access_token=mkb6g9322wzzkl616btn631cezhbrq&scope=user_read+user_subscriptions+user_follows_edit+chat_login&state=ec4511926d183022e43bd5042dbdf06a

		if !params.has_key?(:hash)
			redirect_to code_token_error_path			
			return
		end

		# remove first char
		hash = params[:hash].slice(1, params[:hash].length - 1) 
		hash_components = hash.split("&") # Should be 3 components at this point, access_token, scope and state

		hash_lookup = {}

		hash_components.each do |hc|
			hcc = hc.split("=") # Splits into key/val
			hash_lookup[hcc[0].to_sym] = hcc[1]
		end

		# We can identify the transaction using the state/nonce value we passed originally
		# Otherwise we're going to have to store the code in a session value
		# because it can't be passed through the Twitch.tv API otherwse. If we can avoid
		# managing a session variable, then great
		state = hash_lookup[:state]

		@code = Code.where(:state => hash_lookup[:state]).first
		if @code == nil
			redirect_to code_token_error_path
			return
		end

		@code.user_token = hash_lookup[:access_token]
		if @code.save
			redirect_to code_token_done_path			
		else
			redirect_to code_token_error_path			
		end	
	end

	def code_token_done

	end

	def process_code

		code = params[:code].downcase.gsub(/\s+/, "")

		@code = Code.where(:code => code).first
		if @code == nil
			redirect_to code_error_path
			return
		end

		request_url = "https://api.twitch.tv/kraken/oauth2/authorize?response_type=token" +
			"&client_id=#{Rails.application.secrets.twitch_client_id}" +
			"&redirect_uri=http://twitchy.jeon.com.au/code/token"+
		    "&scope=user_read+user_subscriptions+user_follows_edit+chat_login"+
		    "&state=#{@code.state}"

		redirect_to request_url
		return
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/_code_form.html.erb
<%= form_tag(process_code_path, :class => "form form-horizontal", :role => "form", :id => "code-form") do |f| %>			
	<div class="col-sm-12">
		<div class="form-group">
			<%= text_field_tag :code, nil, { :class => "form-control input-lg", :placeholder => "Code", :maxlength => 9 } %>								
		</div>
	</div>	
	<div class="col-sm-12">
		<div class="form-group">
			<button class="btn btn-block btn-lg" type="submit">Login</button>								
		</div>
	</div>				
<% end %>

app/views/index/code.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">

			<%= image_tag('twitchy-logo', :retina => true, :alt => "Twitchy Logo", :class => "login-logo") %>
			<p class="login-text">Enter your code below to proceed with login:</p>

			<hr />

			<%= render :partial => "code_form" %>

			<hr />

		</div>
	</div>
</div>

app/views/index/code_error.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">

			<%= image_tag('twitchy-logo', :retina => true, :alt => "Twitchy Logo", :class => "login-logo") %>
			<p class="login-text">Enter your code below to proceed with login:</p>

			<hr />

			<div class="alert alert-danger">
				<p>Could not process your code. It may have expired or was entered incorrectly. Please try generating a new code from the Twitchy app.</p>
			</div>
			
			<%= render :partial => "code_form" %>

		</div>
	</div>
</div>

app/views/index/code_token.html.erb
<%= form_tag(code_token_save_path, :class => "form form-horizontal", :role => "form", :id => "hash-form", :style => "display: none;") do |f| %>
	<div class="col-sm-12">
		<div class="form-group">
			<%= hidden_field_tag :hash, nil, { :class => "form-control" } %>								
		</div>
	</div>				
<% end %>

<script type="text/javascript">
	var hash = document.location.hash;

	$("input#hash").val(hash);
	$("form#hash-form").submit();
</script>

app/views/index/code_token_done.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">

			<%= image_tag('twitchy-logo', :retina => true, :alt => "Twitchy Logo", :class => "login-logo") %>
			<hr />

			<div class="alert alert-success">
				<p>You have successfully signed into Twitchy with your Twitch.tv account. Please now return to the TV app.</p>
			</div>			

			<hr />

		</div>
	</div>
</div>

app/views/index/code_token_error.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">

			<%= image_tag('twitchy-logo', :retina => true, :alt => "Twitchy Logo", :class => "login-logo") %>
			<hr />

			<div class="alert alert-danger">
				<p>Twitch.tv servers gave an unexpected response. Please try again later.</p>
			</div>			

			<hr />

		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitchy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<meta name="viewport" content="width=device-width" />   
</head>
<body>

<body>

    <div id="wrapper" class="wrapper <%= params[:controller] %>.<%= params[:action] %>">      

        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

            <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %> alert-dismissible" role="alert">

                    <button type="button" class="close" data-dismiss="alert">
                      <span aria-hidden="true">&times;</span>
                      <span class="sr-only">Close</span>
                    </button>
                    
                    <%= value %>
                </div>
            <% end %>

            <%= yield %>
        </div>
    </div>
</body>

</body>
</html>